### PR TITLE
Keep track of fallthrough value to avoid false decrement

### PR DESCRIPTION
**Pull request by raJeev-M**
Cause: https://github.com/uNetworking/uSockets/issues/52

### CODE REVIEW

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uSockets/blob/9136f22fdaeac72d94a4d79c6c64fba1e6c7366e/src/loop.c#L23

https://github.com/uNetworking/uSockets/blob/9136f22fdaeac72d94a4d79c6c64fba1e6c7366e/src/loop.c#L35

Fallthrough polls are used pretty much only for internal timers and internal "asyncs" when creating a loop. It makes sense to only keep track/support fallthrough polls that are asyncs or timers, since those are rarely constructed.

**Comment by raJeev-M** [comment]
@alexhultman, Thank you for the response. I've come across those two polls before making this change, but for some weird reason I thought like-- what if there might be more fallthrough polls added in the future? (looks like we won't be).

Off the top of my head, one solution which I am currently thinking that requires no change in the interface as well as any Type is: directly calling `free()` in both `timer/async_close` function, rather than doing it via `us_poll_free`.

**Comment by alexhultman** [comment]
You can probably just make all polls increment the poll counter but if the poll is a fallthrough then also increment the threshold at where the loop falls through?

**Comment by alexhultman** [comment]
So if you have 5 polls where 2 are fallthrough then loop has counters 5 and 2 and every free decrements the total but not the threshold

**Comment by raJeev-M** [comment]
@alexhultman, I am thinking like, do we really need any change (adding threshold/ if..else) for the 2 fallthrough polls we are currently having? how about the below approach?

In` us_create_poll()` we do have an `if` statement for incrementing the 'num_polls', so, if we have two fallthrough polls, but zero non-fallthrough polls then the `num_polls` going to be zero, and with this being the case

we can add an one-line change under `us_poll_free()` like `loop->num_polls? loop->num_polls-- : 0`

would that be an acceptable change?

**Pull request closed without merging**
