### PR TITLE
Only define WIN32_EXPORT if LIBUS_BUILDING_DLL is defined

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/uNetworking/uSockets/issues/184

### CODE REVIEW

**Comment by uNetworkingAB** [comment]
But this is not the fix we discussed

**Comment by traversaro** [comment]
I implemented what suggested in https://github.com/uNetworking/uSockets/issues/184 . I avoided to use the generic `_DLL` macro as the `libusockets.h` file is included also in compilation units that are not the `uSockets` ones, and in that case you do not want to `WIN32_EXPORT` to be define to `__declspec(dllexport)` , so it is useful to avoid to use the `_DLL` generic macro and use instead a uSockets-specific macro.

**Comment by traversaro** [comment]
> But this is not the fix we discussed

By bad, I added the explanatory comment later in the PR, sorry for that.

**Comment by traversaro** [comment]
Superseded by https://github.com/uNetworking/uSockets/issues/184 .

**Pull request closed without merging**
